### ISSUE TITLE
Provide a more realistic example

### ISSUE THREAD

**Issue by garak** [eljam/circuit-breaker#11]
Documentation is currently providing a single example, that doesn't explain so much.
The example mentions a GitHub API, but then no reference to any call is shown in the code (not even in an abstract way, e.g. via code comments).

**Comment by gcavana-ouicar** [comment]
Hello @garak , thank you for your comment.

Actually, the library is pretty simple and doesn't show implementation in a framework like symfony or laravel, but happy to provide more if needed if you can share what you want to achieve with this library.

**Comment by eljam** [comment]
Hello @garak , thank you for your comment.

Actually, the library is pretty simple and doesn't show implementation in a framework like symfony or laravel, but happy to provide more if needed if you can share what you want to achieve with this library.

**Comment by garak** [comment]
Thanks for the prompt reply. I wasn't thinking about high-level integration, but I feel like the example is missing something basic.
For example, maybe adding some more comments in the call of `protect`  method could be helpful

**Comment by eljam** [comment]
Ok we'll do.
