### ISSUE TITLE
Replace AbstractAdapter with AdapterInterface

### ISSUE THREAD

**Issue by garak** [eljam/circuit-breaker#12]
The current implementation of Breaker class requires to inject `\Symfony\Component\Cache\Adapter\AbstractAdapter`.
I think it should type hint for more generic `\Symfony\Component\Cache\Adapter\AdapterInterface`, since the concrete object makes harder to use dependency injection (for example, with Symfony).

I can provide a PR.

**Comment by eljam** [comment]
Yes good catch !
