### ISSUE TITLE
PHP 5.4 compatibility

### ISSUE THREAD

**Issue by guilhermednt** [eljam/circuit-breaker#4]
Any chance you'd be willing to make this PHP 5.4-compatible?

I'm currently using `ejsmont-artur/php-circuit-breaker` but your solution seems more elegant and I'd like to give it a try.

(I know 5.4 is dead, but Red Hat insists on using it and in my company they don't allow installing anything that is not Red Hat-approved -- they won't even use Red Hat Software Collections, go figure...)

**Comment by gcavana** [comment]
Hi, well i can give it a try as most of the components in this library are from symfony 2.8 that is compatible with 5.3.9. I will try this tomorrow or if you can create a pull request to add 5.4 before it would be great :)

**Comment by guilhermednt** [comment]
I've managed to get it working on PHP 5.4 on a fork and I'd be happy to send a PR but first I think it'd be wise to check on issue #5 more thoroughly to make sure it's not related to the changes I've made.
