### ISSUE TITLE
Cache::contains() not reliable?

### ISSUE THREAD

**Issue by guilhermednt** [eljam/circuit-breaker#5]
I've noticed Doctrine's `Cache::contains()` is always returning `true` when using `MemcacheCache`.

``` php
    // on Breaker.php
    protected function loadCircuit($name)
    {
        if ($this->store->contains($name)) {
            $circuit = $this->store->fetch($name); // always true when using MemcacheCache
        } else {
            $circuit = new Circuit($name);
        }
    // ...
```

Would it be a problem if we just checked for a `false` response on `fetch()` or are there known issues with other cache drivers?

[It seems](https://github.com/doctrine/cache/blob/8aad38df556fb46f43d950f428c398ccfe93179c/lib/Doctrine/Common/Cache/Cache.php#L53) this would not be a problem:

> @return mixed The cached data or FALSE, if no cache entry exists for the given id.

**Comment by guilhermednt** [comment]
I changed it to the following as a quick fix locally just to be able to test the lib under PHP 5.4 (#4) and it worked fine so far.

``` php
    $circuit = $this->store->fetch($name) ?: new Circuit($name);
```

**Comment by eljam** [comment]
Yes fetch should be more reliable than contains.

**Comment by eljam** [comment]
fix with https://github.com/eljam/circuit-breaker/tree/v0.1.2. Goo catch !
